In [1]:
import numpy as np
import numpy as sy
a = np.array([[1,3,-2],[2,1,3],[1,3,9]]) # matrik 3x3
b = np.array([[3,0,4],[0,-1,2],]) #matriks 2x3
c = np.array([[2,1],[2,3],[3,5]]) # matriks 3x2
D = np.array([[1,3,-2],[2,1,4],[3,2,1]]) #matriks 3x3
print(c)
print(b)

[[2 1]
 [2 3]
 [3 5]]
[[ 3  0  4]
 [ 0 -1  2]]


In [2]:
# CONTOH
import numpy as np
import numpy as sy
a = np.array([[1,3,],[2,1,]]) #matriks 2x2
b = np.array([[3,0,4],[-1,-2,1]]) #3x3
c = np.array([[-2,1],[4,1]]) #2x2
d = np.array([[2],[6]]) #1x1
print (d)
print (b)

[[2]
 [6]]
[[ 3  0  4]
 [-1 -2  1]]


In [ ]:
# Mengalikan matriks A dan B
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]


In [4]:
a = [[2,3,4],
     [4,2,1],
     ]
