## Aljabar matriks

- berikan penjelasan tentang apa itu matrik
- operasi matrik
- buat program untuk mengalikan matrik a dan b
- buatlah matrix A(3X3) B (2X3) C(3X2)

In [ ]:
import numpy as np
import numpy as sy
a = np.array([[1,3,-2],[2,1,3],[1,3,9]]) # matrik 3x3
b = np.array([[3,0,4],[0,-1,2],]) #matriks 2x3
c = np.array([[2,1],[2,3],[3,5]]) # matriks 3x2
D = np.array([[1,3,-2],[2,1,4],[3,2,1]]) #matriks 3x3
print(c)
print(b)

[[2 1]
 [2 3]
 [3 5]]
[[ 3  0  4]
 [ 0 -1  2]]


In [ ]:
# CONTOH
import numpy as np
import numpy as sy
a = np.array([[1,3,],[2,1,]]) #matriks 2x2
b = np.array([[3,0,4],[-1,-2,1]]) #3x3
c = np.array([[-2,1],[4,1]]) #2x2
d = np.array([[2],[6]]) #1x1
print (d)
print (b)


[[2]
 [6]]
[[ 3  0  4]
 [-1 -2  1]]


In [ ]:
a=np.array([[1,0],[0,1]])
print('a=',a)
print()
b=np.array([[-2,1,2],[4,1,3]])
print('b=', b)
print()
print('axb=',a@b)

a= [[1 0]
 [0 1]]

b= [[-2  1  2]
 [ 4  1  3]]

axb= [[-2  1  2]
 [ 4  1  3]]


In [ ]:
# tranfos
a = np.array

**JAWABAN DARI SOAL YANG DIATAS**

1. Berikan penjelasan tentang apa itu matrik

Matriks adalah sebuah himpunan bilangan yang disusun dalam bentuk tabel berupa baris dan kolom. Setiap elemen di dalam matriks diletakkan di suatu posisi yang dapat diidentifikasi melalui indeks baris dan indeks kolomnya. Sebagai contoh, matriks A dengan m baris dan
n kolom dapat dituliskan dalam bentuk:


a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \]
Di sini, \( a_{ij} \) merupakan elemen matriks yang terletak pada baris ke-\( i \) dan kolom ke-\
( j \).

Matriks memiliki berbagai macam aplikasi dalam matematika, ilmu komputer, dan berbagai bidang lainnya. Beberapa aplikasi umum dari matriks termasuk dalam sistem persamaan linear, transformasi geometri, analisis jaringan, analisis data, dan banyak lagi.
Operasi yang umum dilakukan terhadap matriks termasuk penjumlahan, pengurangan, perkalian, dan transposisi. Perkalian matriks, khususnya, adalah operasi yang penting dan memiliki beragam aplikasi dalam berbagai bidang, seperti transformasi linier, optimisasi, dan pemrosesan sinyal.










In [1]:
import numpy as np
A = np.array([[1, 3, 3],[2, 1, 9],[2, 4, 7]])
B = np.array([[1,6,3],[2,8,7],[3,9,5]]) #3x3
C = np.array([[2,4],[5,2],[6,7]]) #3x2
D = np.array([[3,7,5],[1,4,8],[2,4,5]])
E = A+B #penjumlahan
F = 2*A #Skala
G = A@C #perkalian
H = B@C
I = A@H
J = A@B
K = J@C
L = A-B #pengurangan

C_trans = C.transpose()
Z = C_trans@C
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(I)
print('\n')
print(K)
print('\n')
print(L)
print('\n')
print(C_trans)
print(Z)

[[ 2  9  6]
 [ 4  9 16]
 [ 5 13 12]]


[[ 2  6  6]
 [ 4  2 18]
 [ 4  8 14]]


[[35 31]
 [63 73]
 [66 65]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 0 -3  0]
 [ 0 -7  2]
 [-1 -5  2]]


[[2 5 6]
 [4 2 7]]
[[65 60]
 [60 69]]


In [3]:
# Membuat matriks A dengan ordo 3x3
A = [[3,5,-2],
     [7,1,4],
     [-5,6,2]]

# Membuat matriks B dengan ordo 3x3
B = [[3,1,-2],
     [5,2,7],
     [7,-2,5]]

# Membuat matriks C dengan ordo 3x2
C = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

# Membuat matriks D dengan ordo 3x2
D = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]


# Mengalikan matriks A dan B
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

# Menampilkan hasil perkalian
print("Hasil perkalian matriks A dan B:")
for row in C:
    print(row)


Hasil perkalian matriks A dan B:
[20, 17, 19]
[54, 1, 13]
[29, 3, 62]
