## Aljabar matriks

- berikan penjelasan tentang apa itu matrik
- operasi matrik
- buat program untuk mengalikan matrik a dan b
- buatlah matrix A(3X3) B (2X3) C(3X2)

In [14]:
import numpy as np
import numpy as sy
a = np.array([[1,3,-2],[2,1,3],[1,3,9]]) # matrik 3x3
b = np.array([[3,0,4],[0,-1,2],]) #matriks 2x3
c = np.array([[2,1],[2,3],[3,5]]) # matriks 3x2
D = np.array([[1,3,-2],[2,1,4],[3,2,1]]) #matriks 3x3
print(c)
print(b)

[[2 1]
 [2 3]
 [3 5]]
[[ 3  0  4]
 [ 0 -1  2]]


In [6]:
# CONTOH
import numpy as np
import numpy as sy
a = np.array([[1,3,],[2,1,]]) #matriks 2x2
b = np.array([[3,0,4],[-1,-2,1]]) #3x3
c = np.array([[-2,1],[4,1]]) #2x2
d = np.array([[2],[6]]) #1x1
print (d)
print (b)


[[2]
 [6]]
[[ 3  0  4]
 [-1 -2  1]]


In [15]:
a=np.array([[1,0],[0,1]])
print('a=',a)
print()
b=np.array([[-2,1,2],[4,1,3]])
print('b=', b)
print()
print('axb=',a@b)

a= [[1 0]
 [0 1]]

b= [[-2  1  2]
 [ 4  1  3]]

axb= [[-2  1  2]
 [ 4  1  3]]


In [ ]:
# tranfos
a = np.array